# Generated by Django 3.2.8 on 2021-10-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_level_xp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='next_level_xp',
            field=models.IntegerField(default=20),
        ),
    ]
