# Generated by Django 3.2.8 on 2021-10-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211027_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomgame',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
