# Generated by Django 3.2.8 on 2021-10-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_roomgame_in_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomgame',
            name='in_game',
        ),
        migrations.AddField(
            model_name='roomgame',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='game.player'),
        ),
        migrations.AddField(
            model_name='roomgame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='game.player'),
        ),
    ]
