# Generated by Django 3.2.8 on 2022-01-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20220108_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomgame',
            name='game_situation',
            field=models.CharField(choices=[('IG', 'In Game'), ('EG', 'End Game')], default='IG', max_length=2),
        ),
    ]
