# Generated by Django 3.2.8 on 2022-01-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_roomgame_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomgame',
            name='player1_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='roomgame',
            name='player2_hp',
            field=models.IntegerField(default=100),
        ),
    ]
