# Generated by Django 3.2.8 on 2022-01-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20220109_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomgame',
            name='game_log',
            field=models.TextField(default='[]'),
        ),
    ]
